package de.jhoopmann.topmostwindow.awt.ui

actual val DefaultPlatformInitializeParent: InitializeParentFunction = DefaultInitializeParent

actual val DefaultPlatformBeforeInitialization: InitializationEvent = DefaultBeforeInitialization

actual val DefaultPlatformAfterInitialization: InitializationEvent = DefaultAfterInitialization
