name: Publish to GitHub Packages

on:
    push:
        branches:
            - publish

jobs:
    platform_matrix:
        strategy:
            fail-fast: false
            matrix:
                system_image:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
                include:
                    - system_image: macos-latest
                      system_architecture: aarch64
                      target_jvm_platform: macos
                    - system_image: ubuntu-latest
                      system_architecture: x64
                      target_jvm_platform: linux
                    - system_image: windows-latest
                      system_architecture: x64
                      target_jvm_platform: mingw
                      
        runs-on: ${{ matrix.system_image }}
        steps:
            - name: Install X11 Headers
              if: matrix.target_jvm_platform == 'linux'
              run: sudo apt update && sudo apt install -y libx11-dev

            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup JDK
              uses: actions/setup-java@4.7.0
              with:
                  distribution: oracle
                  java-version: "21"
                  architecture: ${{ matrix.system_architecture }}

            - name: Grant execute permission for Gradle
              run: chmod +x gradlew

            - name: Publish Package
              run: ./gradlew publishTargetJvmPlatformPublicationToGithubRepository -PtargetJvmPlatform=${{ matrix.target_jvm_platform }}
              env:
                  GITHUB_ACTOR: ${{ github.actor }}
                  GITHUB_TOKEN: ${{ secrets.PUBLISHING_TOKEN }}
                  